// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_full_combo = "CgkI_OfM-7wYEAIQAw"; // <GPGSID>
        public const string achievement_not_a_disaster = "CgkI_OfM-7wYEAIQAQ"; // <GPGSID>
        public const string achievement_captain = "CgkI_OfM-7wYEAIQBw"; // <GPGSID>
        public const string achievement_perfect_accuracy = "CgkI_OfM-7wYEAIQBQ"; // <GPGSID>
        public const string leaderboard_cubic_pilot_hall_of_fame = "CgkI_OfM-7wYEAIQCQ"; // <GPGSID>
        public const string achievement_clear_all_levels = "CgkI_OfM-7wYEAIQBA"; // <GPGSID>
        public const string achievement_sargent = "CgkI_OfM-7wYEAIQBg"; // <GPGSID>
        public const string achievement_point_blank = "CgkI_OfM-7wYEAIQAg"; // <GPGSID>
        public const string achievement_admiral = "CgkI_OfM-7wYEAIQCA"; // <GPGSID>

}

